mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: false
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: ۱ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: fdc48be3-a615-41ac-8bd1-ed844c931048
  udp: true
  tls: true
  servername: edgetunnel-4uw.pages.dev
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /fp=chrome
    headers:
      Host: edgetunnel-4uw.pages.dev
- name: ۲ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 9e3132b8-b595-444a-833a-2de44789f9d7
  udp: true
  tls: true
  servername: shephe.dpdns.org
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /?Telegram---PLANB_NET---PLANB_NET---PLANB_NET---PLANB_NET
    headers:
      Host: shephe.dpdns.org
- name: ۳ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 3c6d1933-b22a-484b-ac8a-63e24f5fba75
  udp: true
  tls: true
  servername: server9.9966338.xyz
  skip-cert-verify: false
  alpn:
  - h2
  - http/1.1
  network: ws
  ws-opts:
    path: /imnotarealherox
    headers:
      Host: server9.9966338.xyz
- name: ۴ - زن زندگی آزادی 🇳🇱
  type: vless
  server: nl2.404vn.space
  port: 37951
  uuid: 25284368-40d5-4abe-9f56-54a07e88a7af
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: nl2.404vn.space
  reality-opts:
    public-key: O6ZOpoz4sxon8iHxCd5EEvx2K9NUThd4SvOCBEvADEI
    short-id: a9e21fd097d019c6
  client-fingerprint: firefox
- name: ۵ - زن زندگی آزادی 🇨🇦
  type: trojan
  server: www.speedtest.net
  port: 443
  password: humanity
  udp: true
  sni: www.calmlunch.com
  skip-cert-verify: false
  alpn:
  - h2
  - http/1.1
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmlunch.com
- name: ۶ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 77dc177b-79d9-49ac-92e1-2f1011faa5e3
  udp: true
  tls: true
  servername: f871a986.69lover.site
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /api/v2/b8ee4ba356df307c/stream
    headers:
      Host: f871a986.69lover.site
- name: /?TELEGRAM--MARAMBASHI--MARAMBASHI?ed=512&security=tls&encryption=none&insecure=0&host=a.cwvps.eu.org&ech=ip.gs+udp://8.8.8.8&type=ws&allowInsecure=0&sni=a.cwvps.eu.org#۷
    - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: c4edb87e-8544-4fa4-bd1c-b0cda9a34b46
  udp: true
  tls: true
  servername: 188.114.97.6
  skip-cert-verify: false
  alpn:
  - h2
  - http/1.1
- name: ۸ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 38415950-f815-4ca8-94d0-6cbf22be7566
  udp: true
  tls: true
  servername: asia.csmasterofficial.store
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /cs
    headers:
      Host: asia.csmasterofficial.store
- name: ۹ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 4e4f1f70-5e56-4a76-bb9d-db087f4690c4
  udp: true
  tls: true
  servername: jp3.yohototo.top
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /tyxyws
    headers:
      Host: jp3.yohototo.top
- name: 'Telegram------mtmvpn---mtmvpn&sni=www.ignitelimit.com&alpn=http/1.1&fp=unsafe&cs=TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256&fm={"tcp":
    [{"type": "fragment", "settings": {"packets": "tlshello", "lengths": ["0", "104",
    "1"], "delays": ["0"], "maxSplit": "0"}},{"type": "fragment", "settings": {"packets":
    "1-1", "lengths": ["114", "1"], "delays": ["1"], "maxSplit": "11"}}]}#۱۰ - زن
    زندگی آزادی 🇨🇦'
  type: trojan
  server: 188.114.97.6
  port: 443
  password: humanity
  udp: true
  sni: 188.114.97.6
  skip-cert-verify: false
  alpn:
  - h2
  - http/1.1
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: ۱۱ - زن زندگی آزادی 🇨🇦
  type: vless
  server: 188.114.97.6
  port: 443
  uuid: 91d28760-ecf1-450b-9170-d310111a0e6d
  udp: true
  tls: true
  servername: edfc774f.69lover.site
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: unsafe
  network: ws
  ws-opts:
    path: /api/v2/63e9687fa53e441c/stream
    headers:
      Host: edfc774f.69lover.site
proxy-groups:
- name: زن زندگی آزادی
  type: select
  proxies:
  - بهترین پینگ
  - ۱ - زن زندگی آزادی 🇨🇦
  - ۲ - زن زندگی آزادی 🇨🇦
  - ۳ - زن زندگی آزادی 🇨🇦
  - ۴ - زن زندگی آزادی 🇳🇱
  - ۵ - زن زندگی آزادی 🇨🇦
  - ۶ - زن زندگی آزادی 🇨🇦
  - /?TELEGRAM--MARAMBASHI--MARAMBASHI?ed=512&security=tls&encryption=none&insecure=0&host=a.cwvps.eu.org&ech=ip.gs+udp://8.8.8.8&type=ws&allowInsecure=0&sni=a.cwvps.eu.org#۷
    - زن زندگی آزادی 🇨🇦
  - ۸ - زن زندگی آزادی 🇨🇦
  - ۹ - زن زندگی آزادی 🇨🇦
  - 'Telegram------mtmvpn---mtmvpn&sni=www.ignitelimit.com&alpn=http/1.1&fp=unsafe&cs=TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256&fm={"tcp":
    [{"type": "fragment", "settings": {"packets": "tlshello", "lengths": ["0", "104",
    "1"], "delays": ["0"], "maxSplit": "0"}},{"type": "fragment", "settings": {"packets":
    "1-1", "lengths": ["114", "1"], "delays": ["1"], "maxSplit": "11"}}]}#۱۰ - زن
    زندگی آزادی 🇨🇦'
  - ۱۱ - زن زندگی آزادی 🇨🇦
  - DIRECT
- name: بهترین پینگ
  type: url-test
  proxies:
  - ۱ - زن زندگی آزادی 🇨🇦
  - ۲ - زن زندگی آزادی 🇨🇦
  - ۳ - زن زندگی آزادی 🇨🇦
  - ۴ - زن زندگی آزادی 🇳🇱
  - ۵ - زن زندگی آزادی 🇨🇦
  - ۶ - زن زندگی آزادی 🇨🇦
  - /?TELEGRAM--MARAMBASHI--MARAMBASHI?ed=512&security=tls&encryption=none&insecure=0&host=a.cwvps.eu.org&ech=ip.gs+udp://8.8.8.8&type=ws&allowInsecure=0&sni=a.cwvps.eu.org#۷
    - زن زندگی آزادی 🇨🇦
  - ۸ - زن زندگی آزادی 🇨🇦
  - ۹ - زن زندگی آزادی 🇨🇦
  - 'Telegram------mtmvpn---mtmvpn&sni=www.ignitelimit.com&alpn=http/1.1&fp=unsafe&cs=TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256&fm={"tcp":
    [{"type": "fragment", "settings": {"packets": "tlshello", "lengths": ["0", "104",
    "1"], "delays": ["0"], "maxSplit": "0"}},{"type": "fragment", "settings": {"packets":
    "1-1", "lengths": ["114", "1"], "delays": ["1"], "maxSplit": "11"}}]}#۱۰ - زن
    زندگی آزادی 🇨🇦'
  - ۱۱ - زن زندگی آزادی 🇨🇦
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- GEOSITE,category-ads-all,REJECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- MATCH,زن زندگی آزادی
