mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: false
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: ۶ - زن زندگی آزادی 🇨🇦
  type: ss
  server: 51.222.12.127
  port: 445
  cipher: aes-256-gcm
  password: zDNVedRFPQexG9v
  udp: true
- name: ۸ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 169.40.42.179
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: yahoo.com
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
  client-fingerprint: ios
- name: ۹ - زن زندگی آزادی 🇨🇦
  type: ss
  server: 15.235.75.71
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: FD3rCuOsxOay
  udp: true
- name: ۱۰ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 47.253.226.114
  port: 443
  uuid: 055a1ce8-2a16-4a0d-a2c2-22826c9b2413
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.cloudflare.com
  reality-opts:
    public-key: Svl81isn16RPAFnjtmYw7A6TPnsEPLHuYYaJht65Rzc
    short-id: ''
  client-fingerprint: chrome
- name: ۱۲ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 169.40.42.173
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: yahoo.com
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
  client-fingerprint: ios
- name: ۱۴ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 169.40.42.15
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: yahoo.com
  reality-opts:
    public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
    short-id: c39cc7310a
  client-fingerprint: firefox
- name: ۱۸ - زن زندگی آزادی 🇺🇸
  type: vmess
  server: 82.198.246.250
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
- name: ۱۹ - زن زندگی آزادی 🇺🇸
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
- name: ۲۰ - زن زندگی آزادی 🇺🇸
  type: vmess
  server: 82.198.246.233
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
- name: ۲۶ - زن زندگی آزادی 🇺🇸
  type: ss
  server: 108.181.0.177
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: G5p6ww4o67HB
  udp: true
- name: ۲۸ - زن زندگی آزادی 🇫🇷
  type: ss
  server: 51.77.225.200
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: zRZNBszYyWo5
  udp: true
- name: ۲۹ - زن زندگی آزادی 🇺🇸
  type: vmess
  server: 216.106.185.141
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  udp: true
  tls: false
- name: ۳۲ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 172.235.43.210
  port: 53957
  uuid: 7ab29f89-6eef-4171-b232-fc4f580ad31b
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.nvidia.com
  reality-opts:
    public-key: XUHlbk5VH5z4E2wxZBhlpLZ33qevyQgqU7dheRDgoGQ
    short-id: 44e82fd7b97b14
  client-fingerprint: firefox
- name: ۳۳ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 188.116.23.244
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: eVC634QvVk5l
  udp: true
- name: ۳۴ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 158.173.20.208
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
  udp: true
- name: ۳۵ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.219
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۳۶ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.216
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۳۷ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.214
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۳۸ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.198
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۳۹ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.197
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۴۰ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 193.29.139.234
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: 4a2rfixophdjffa8KVA4Aa
  udp: true
- name: ۴۱ - زن زندگی آزادی 🇫🇷
  type: ss
  server: 51.255.13.232
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: BqnqToih0PbU
  udp: true
- name: ۴۲ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.201
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
- name: ۴۳ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.205
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
- name: ۴۵ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.179
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
- name: ۴۶ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.13
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
- name: ۴۷ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 15.204.97.206
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۴۸ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.162
  port: 443
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
- name: ۴۹ - زن زندگی آزادی 🇺🇸
  type: vless
  server: 107.173.237.146
  port: 8443
  uuid: 1d39f715-2740-4d99-bc3b-197cc48dcee7
  udp: true
  tls: true
  servername: updates.cdn-apple.com
  reality-opts:
    public-key: D3ojIs3AUKP_tV0E4TEjh90HBVJp24Nq3qMfdxD30kc
    short-id: df8611c07d
  client-fingerprint: chrome
- name: ۵۰ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 82.38.31.218
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
- name: ۵۲ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.34
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۵۳ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.26
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۵۴ - زن زندگی آزادی 🇳🇱
  type: ss
  server: 108.181.58.239
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: CJmTCCx7Ltud
  udp: true
- name: ۵۶ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.25
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۵۸ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.96
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۶۱ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.103
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۶۲ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.19
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۶۳ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.86
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۶۴ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.98
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۶۶ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.93
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۶۷ - زن زندگی آزادی 🇷🇺
  type: vless
  server: 113.30.154.2
  port: 443
  uuid: db9da8fb-c528-42ec-9b9e-e578cf934c04
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: sellflow.org
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: ''
  client-fingerprint: firefox
- name: ۶۸ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.8
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
  client-fingerprint: chrome
- name: ۶۹ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 193.23.194.167
  port: 8443
  uuid: 32349ee8-8551-45fa-a265-8704cec72936
  udp: true
  tls: true
  servername: neth.lckdwn.ru
  skip-cert-verify: false
  alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
- name: ۷۰ - زن زندگی آزادی 🇩🇪
  type: ss
  server: 185.226.172.8
  port: 8008
  cipher: aes-256-gcm
  password: XKFKl2rULjIp74
  udp: true
- name: ۷۱ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.20
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۷۲ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.97
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۷۴ - زن زندگی آزادی 🇫🇷
  type: vless
  server: 103.91.147.16
  port: 443
  uuid: db9da8fb-c528-42ec-9b9e-e578cf934c04
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: sellflow.org
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: ''
  client-fingerprint: firefox
- name: ۷۵ - زن زندگی آزادی 🇺🇸
  type: trojan
  server: 8.47.69.0
  port: 443
  password: humanity
  udp: true
  sni: www.pleadcourt.org
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.pleadcourt.org
- name: ۷۶ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.80
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۷۷ - زن زندگی آزادی 🇱🇹
  type: ss
  server: 144.31.243.2
  port: 16015
  cipher: chacha20-ietf-poly1305
  password: J1InuU6QRT5JOh1mQfkjU2
  udp: true
- name: ۷۸ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 51.158.206.29
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
- name: ۸۲ - زن زندگی آزادی 🇬🇧
  type: vless
  server: 83.147.18.3
  port: 443
  uuid: 9f61cdf4-810d-4052-bbc7-2da0c8e20104
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.cloudflare.com
  reality-opts:
    public-key: 3iVJAIGPx6JMlhlRmfpGrHkSmLpHJ4CPvBBH7KsFrFA
    short-id: fd8cf7e1173f0edb
- name: ۸۴ - زن زندگی آزادی 🇫🇷
  type: vless
  server: 162.19.10.99
  port: 443
  uuid: e8b1500b-e9e8-5492-8312-f4eadf7d0767
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: nasnet-162191099-direct.mbghalibaf.com
  skip-cert-verify: false
  alpn:
  - h2
  client-fingerprint: chrome
- name: ۸۶ - زن زندگی آزادی 🇳🇱
  type: vless
  server: 193.57.9.120
  port: 443
  uuid: e8dac4fa-295c-4232-8279-2fe14b312a42
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.amazon.com
  reality-opts:
    public-key: gX_OQ9oJNQCtWdQC4lnOEYatfYA-vvVrGvPAzh6Zbxw
    short-id: a1b2c3d4e5f60718
  client-fingerprint: firefox
- name: ۸۸ - زن زندگی آزادی 🇪🇸
  type: trojan
  server: 213.182.199.137
  port: 443
  password: humanity
  udp: true
  sni: www.pleadcourt.org
  skip-cert-verify: false
  alpn:
  - http/1.1
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: /assignment
    headers:
      Host: www.pleadcourt.org
- name: ۱۰۰ - زن زندگی آزادی 🇺🇸
  type: vless
  server: ww13.levikogjgfdd.ir
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: fuck.rkn
  reality-opts:
    public-key: 1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s
    short-id: '01'
proxy-groups:
- name: زن زندگی آزادی
  type: select
  proxies:
  - بهترین پینگ
  - ۶ - زن زندگی آزادی 🇨🇦
  - ۸ - زن زندگی آزادی 🇺🇸
  - ۹ - زن زندگی آزادی 🇨🇦
  - ۱۰ - زن زندگی آزادی 🇺🇸
  - ۱۲ - زن زندگی آزادی 🇺🇸
  - ۱۴ - زن زندگی آزادی 🇺🇸
  - ۱۸ - زن زندگی آزادی 🇺🇸
  - ۱۹ - زن زندگی آزادی 🇺🇸
  - ۲۰ - زن زندگی آزادی 🇺🇸
  - ۲۶ - زن زندگی آزادی 🇺🇸
  - ۲۸ - زن زندگی آزادی 🇫🇷
  - ۲۹ - زن زندگی آزادی 🇺🇸
  - ۳۲ - زن زندگی آزادی 🇺🇸
  - ۳۳ - زن زندگی آزادی 🇳🇱
  - ۳۴ - زن زندگی آزادی 🇳🇱
  - ۳۵ - زن زندگی آزادی 🇺🇸
  - ۳۶ - زن زندگی آزادی 🇺🇸
  - ۳۷ - زن زندگی آزادی 🇺🇸
  - ۳۸ - زن زندگی آزادی 🇺🇸
  - ۳۹ - زن زندگی آزادی 🇺🇸
  - ۴۰ - زن زندگی آزادی 🇳🇱
  - ۴۱ - زن زندگی آزادی 🇫🇷
  - ۴۲ - زن زندگی آزادی 🇳🇱
  - ۴۳ - زن زندگی آزادی 🇳🇱
  - ۴۵ - زن زندگی آزادی 🇳🇱
  - ۴۶ - زن زندگی آزادی 🇳🇱
  - ۴۷ - زن زندگی آزادی 🇺🇸
  - ۴۸ - زن زندگی آزادی 🇳🇱
  - ۴۹ - زن زندگی آزادی 🇺🇸
  - ۵۰ - زن زندگی آزادی 🇳🇱
  - ۵۲ - زن زندگی آزادی 🇳🇱
  - ۵۳ - زن زندگی آزادی 🇳🇱
  - ۵۴ - زن زندگی آزادی 🇳🇱
  - ۵۶ - زن زندگی آزادی 🇳🇱
  - ۵۸ - زن زندگی آزادی 🇳🇱
  - ۶۱ - زن زندگی آزادی 🇳🇱
  - ۶۲ - زن زندگی آزادی 🇳🇱
  - ۶۳ - زن زندگی آزادی 🇳🇱
  - ۶۴ - زن زندگی آزادی 🇳🇱
  - ۶۶ - زن زندگی آزادی 🇳🇱
  - ۶۷ - زن زندگی آزادی 🇷🇺
  - ۶۸ - زن زندگی آزادی 🇳🇱
  - ۶۹ - زن زندگی آزادی 🇳🇱
  - ۷۰ - زن زندگی آزادی 🇩🇪
  - ۷۱ - زن زندگی آزادی 🇳🇱
  - ۷۲ - زن زندگی آزادی 🇳🇱
  - ۷۴ - زن زندگی آزادی 🇫🇷
  - ۷۵ - زن زندگی آزادی 🇺🇸
  - ۷۶ - زن زندگی آزادی 🇳🇱
  - ۷۷ - زن زندگی آزادی 🇱🇹
  - ۷۸ - زن زندگی آزادی 🇳🇱
  - ۸۲ - زن زندگی آزادی 🇬🇧
  - ۸۴ - زن زندگی آزادی 🇫🇷
  - ۸۶ - زن زندگی آزادی 🇳🇱
  - ۸۸ - زن زندگی آزادی 🇪🇸
  - ۱۰۰ - زن زندگی آزادی 🇺🇸
  - DIRECT
- name: بهترین پینگ
  type: url-test
  proxies:
  - ۶ - زن زندگی آزادی 🇨🇦
  - ۸ - زن زندگی آزادی 🇺🇸
  - ۹ - زن زندگی آزادی 🇨🇦
  - ۱۰ - زن زندگی آزادی 🇺🇸
  - ۱۲ - زن زندگی آزادی 🇺🇸
  - ۱۴ - زن زندگی آزادی 🇺🇸
  - ۱۸ - زن زندگی آزادی 🇺🇸
  - ۱۹ - زن زندگی آزادی 🇺🇸
  - ۲۰ - زن زندگی آزادی 🇺🇸
  - ۲۶ - زن زندگی آزادی 🇺🇸
  - ۲۸ - زن زندگی آزادی 🇫🇷
  - ۲۹ - زن زندگی آزادی 🇺🇸
  - ۳۲ - زن زندگی آزادی 🇺🇸
  - ۳۳ - زن زندگی آزادی 🇳🇱
  - ۳۴ - زن زندگی آزادی 🇳🇱
  - ۳۵ - زن زندگی آزادی 🇺🇸
  - ۳۶ - زن زندگی آزادی 🇺🇸
  - ۳۷ - زن زندگی آزادی 🇺🇸
  - ۳۸ - زن زندگی آزادی 🇺🇸
  - ۳۹ - زن زندگی آزادی 🇺🇸
  - ۴۰ - زن زندگی آزادی 🇳🇱
  - ۴۱ - زن زندگی آزادی 🇫🇷
  - ۴۲ - زن زندگی آزادی 🇳🇱
  - ۴۳ - زن زندگی آزادی 🇳🇱
  - ۴۵ - زن زندگی آزادی 🇳🇱
  - ۴۶ - زن زندگی آزادی 🇳🇱
  - ۴۷ - زن زندگی آزادی 🇺🇸
  - ۴۸ - زن زندگی آزادی 🇳🇱
  - ۴۹ - زن زندگی آزادی 🇺🇸
  - ۵۰ - زن زندگی آزادی 🇳🇱
  - ۵۲ - زن زندگی آزادی 🇳🇱
  - ۵۳ - زن زندگی آزادی 🇳🇱
  - ۵۴ - زن زندگی آزادی 🇳🇱
  - ۵۶ - زن زندگی آزادی 🇳🇱
  - ۵۸ - زن زندگی آزادی 🇳🇱
  - ۶۱ - زن زندگی آزادی 🇳🇱
  - ۶۲ - زن زندگی آزادی 🇳🇱
  - ۶۳ - زن زندگی آزادی 🇳🇱
  - ۶۴ - زن زندگی آزادی 🇳🇱
  - ۶۶ - زن زندگی آزادی 🇳🇱
  - ۶۷ - زن زندگی آزادی 🇷🇺
  - ۶۸ - زن زندگی آزادی 🇳🇱
  - ۶۹ - زن زندگی آزادی 🇳🇱
  - ۷۰ - زن زندگی آزادی 🇩🇪
  - ۷۱ - زن زندگی آزادی 🇳🇱
  - ۷۲ - زن زندگی آزادی 🇳🇱
  - ۷۴ - زن زندگی آزادی 🇫🇷
  - ۷۵ - زن زندگی آزادی 🇺🇸
  - ۷۶ - زن زندگی آزادی 🇳🇱
  - ۷۷ - زن زندگی آزادی 🇱🇹
  - ۷۸ - زن زندگی آزادی 🇳🇱
  - ۸۲ - زن زندگی آزادی 🇬🇧
  - ۸۴ - زن زندگی آزادی 🇫🇷
  - ۸۶ - زن زندگی آزادی 🇳🇱
  - ۸۸ - زن زندگی آزادی 🇪🇸
  - ۱۰۰ - زن زندگی آزادی 🇺🇸
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- GEOSITE,category-ads-all,REJECT
- DOMAIN-SUFFIX,ir,DIRECT
- GEOIP,IR,DIRECT
- MATCH,زن زندگی آزادی
